FROM erlang:21-alpine

RUN apk add --no-cache --virtual .build-deps \
		dpkg-dev dpkg \
                gcc \
                g++ \
                libc-dev \
                linux-headers \
                make \
                autoconf \
                ncurses-dev \
                openssl-dev \
                unixodbc-dev \
                lksctp-tools-dev \
                tar \
                git \
                wget \
		bsd-compat-headers

