FROM alpine:3.8

RUN apk add --no-cache ncurses-libs openssl

COPY ./emqx ./opt/emqx
COPY ./start.sh /opt/emqx/start.sh

WORKDIR /opt/emqx

CMD ["/opt/emqx/start.sh"]

VOLUME ["/opt/emqx/log", "/opt/emqx/data", "/opt/emqx/lib", "/opt/emqx/etc"]

# emqx will occupy these port:
# - 1883 port for MQTT
# - 8883 port for MQTT(SSL)
# - 8083 for WebSocket/HTTP
# - 8084 for WSS/HTTPS
# - 8080 for mgmt API
# - 18083 for dashboard
# - 4369 for port mapping
# - 5369 for gen_rpc port mapping
# - 6369 for distributed node
EXPOSE 1883 8883 8083 8084 8080 18083 4369 5369 6369 6000-6999
